Repository ndakic/hosting-platform, pull requests merged in 2021-01, with the labels that each got.

#16 project specification
  documentation/1-specification/project specification.docx
  documentation/1-specification/project specification.pdf
  documentation/3-instructions/GitFlow model.pdf
  hostplat-server/src/main/java/META-INF/MANIFEST.MF
Labels: documentation, good first issue

#17 angular material
  hostplat-client/angular.json
  hostplat-client/package-lock.json
  hostplat-client/package.json
  hostplat-client/src/app/app.component.html
  hostplat-client/src/app/app.module.ts
  hostplat-client/src/app/material/material.module.ts
  hostplat-client/src/index.html
  hostplat-client/src/styles.css
Labels: system configuration

#33 exception handling
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/CustomErrorResponse.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/GlobalExceptionHandler.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/ResourceAlreadyExistsException.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/ResourceNotFoundException.java
Labels: back-end, system configuration

#32 Label Model & CRUD Services
  hostplat-server/pom.xml
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/constant/DateTimeConstant.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/constant/LabelStatus.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/constant/Md5Salt.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/LabelEntity.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/repository/LabelRepository.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/resource/LabelResource.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/rest/LabelController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/security/WebSecurity.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/LabelService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/util/DateUtil.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/util/Md5Generator.java
  hostplat-server/src/main/resources/data/data.sql
Labels: back-end

#35 Testing Release/Deploy
  docker-compose.yml
  documentation/1-specification/project specification.docx
  documentation/1-specification/project specification.pdf
  documentation/3-instructions/GitFlow model.pdf
  hostplat-client/Dockerfile
  hostplat-client/angular.json
  hostplat-client/package-lock.json
  hostplat-client/package.json
  hostplat-client/src/app/app.component.html
  hostplat-client/src/app/app.component.ts
  hostplat-client/src/app/app.module.ts
  hostplat-client/src/app/material/material.module.ts
  hostplat-client/src/index.html
  hostplat-client/src/styles.css
  hostplat-server/Dockerfile
  hostplat-server/pom.xml
  hostplat-server/src/main/java/META-INF/MANIFEST.MF
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/constant/DateTimeConstant.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/constant/LabelStatus.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/constant/Md5Salt.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/CustomErrorResponse.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/GlobalExceptionHandler.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/ResourceAlreadyExistsException.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/ResourceNotFoundException.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/LabelEntity.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/repository/LabelRepository.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/resource/LabelResource.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/rest/LabelController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/security/WebSecurity.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/LabelService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/util/DateUtil.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/util/Md5Generator.java
  hostplat-server/src/main/resources/data/data.sql
Labels: devops
