Repository ndakic/hosting-platform, pull requests merged in 2021-02, with the labels that each got.

#37 Exception handling
  documentation/2-postman/UKS PROJECT.postman_collection.json
  hostplat-server/pom.xml
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/common/DeviceProvider.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/common/TimeProvider.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/WebSecurityConfig.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/AuthenticationController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/UserController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/LoginDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/PasswordDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/TokenDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/UserDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/BadRequestException.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/exception/GlobalExceptionHandler.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/Authority.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/User.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/repository/UserRepository.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/security/RestAuthenticationEntryPoint.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/security/TokenAuthenticationFilter.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/security/TokenBasedAuthentication.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/security/TokenUtils.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/UserService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/CustomUserDetailsService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/UserServiceImpl.java
Labels: back-end, enhancement

#39 Support pages branch
  hostplat-client/src/app/app-routing.module.ts
  hostplat-client/src/app/authentication/authentication.module.ts
  hostplat-client/src/app/authentication/login/login.component.css
  hostplat-client/src/app/authentication/login/login.component.html
  hostplat-client/src/app/authentication/login/login.component.spec.ts
  hostplat-client/src/app/authentication/login/login.component.ts
  hostplat-client/src/app/authentication/register/register.component.css
  hostplat-client/src/app/authentication/register/register.component.html
  hostplat-client/src/app/authentication/register/register.component.spec.ts
  hostplat-client/src/app/authentication/register/register.component.ts
  hostplat-client/src/app/core/core.module.ts
  hostplat-client/src/app/pages/forbidden-page/forbidden-page.component.css
  hostplat-client/src/app/pages/forbidden-page/forbidden-page.component.html
  hostplat-client/src/app/pages/forbidden-page/forbidden-page.component.spec.ts
  hostplat-client/src/app/pages/forbidden-page/forbidden-page.component.ts
  hostplat-client/src/app/pages/home-page/home-page.component.css
  hostplat-client/src/app/pages/home-page/home-page.component.html
  hostplat-client/src/app/pages/home-page/home-page.component.spec.ts
  hostplat-client/src/app/pages/home-page/home-page.component.ts
  hostplat-client/src/app/pages/not-found-page/not-found-page.component.css
  hostplat-client/src/app/pages/not-found-page/not-found-page.component.html
  hostplat-client/src/app/pages/not-found-page/not-found-page.component.spec.ts
  hostplat-client/src/app/pages/not-found-page/not-found-page.component.ts
  hostplat-client/src/app/pages/pages.module.ts
  hostplat-client/src/assets/images/400-status-code-bad-request.jpg
  hostplat-client/src/assets/images/401-status-code-unauthorized.jpg
  hostplat-client/src/assets/images/403-status-code-forbidden.jpg
  hostplat-client/src/assets/images/404-status-code-not-found.jpg
  hostplat-client/src/assets/images/500-status-code-internal-server-error.jpg
  hostplat-client/src/assets/images/503-status-code-service-unavailable.jpg
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/security/WebSecurity.java
  hostplat-server/src/main/resources/application.yaml
Labels: enhancement, front-end

#41 Jenkinsfile - Set hostplat dir
  Jenkinsfile
Labels: devops

#105 change avatar feature update
  hostplat-client/src/app/models/user.ts
  hostplat-client/src/app/user/change-avatar/change-avatar.component.css
  hostplat-client/src/app/user/change-avatar/change-avatar.component.html
  hostplat-client/src/app/user/change-avatar/change-avatar.component.ts
  hostplat-client/src/app/user/change-basic-info/change-basic-info.component.ts
  hostplat-client/src/environments/environment.ts
Labels: refactoring

#106 public endpoint fix
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/WebSecurityConfig.java
Labels: back-end

#107 done change avatar feature
  hostplat-client/src/app/core/services/user.service.ts
  hostplat-client/src/app/user/change-avatar/change-avatar.component.ts
  hostplat-client/src/environments/environment.ts
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/CloudinaryConfig.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/UserController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/UserService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/UserServiceImpl.java
  hostplat-server/src/main/resources/application.yaml
Labels: back-end, enhancement, front-end, refactoring

#108 project search and pagination feature
  hostplat-client/src/app/app.module.ts
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.css
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.html
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.spec.ts
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.ts
  hostplat-client/src/app/pages/home-page/home-page.component.css
  hostplat-client/src/app/pages/home-page/home-page.component.html
  hostplat-client/src/app/pages/home-page/home-page.component.ts
  hostplat-client/src/app/pages/pages.module.ts
  hostplat-client/src/app/projects/project.service.ts
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/WebSecurityConfig.java
Labels: back-end, front-end, refactoring

#109 CRUD - Label - front
  hostplat-client/src/app/app-routing.module.ts
  hostplat-client/src/app/app.module.ts
  hostplat-client/src/app/labels/add-label/add-label.component.html
  hostplat-client/src/app/labels/add-label/add-label.component.scss
  hostplat-client/src/app/labels/add-label/add-label.component.spec.ts
  hostplat-client/src/app/labels/add-label/add-label.component.ts
  hostplat-client/src/app/labels/label-details/labal-details.component.spec.ts
  hostplat-client/src/app/labels/label-details/label-details.component.html
  hostplat-client/src/app/labels/label-details/label-details.component.scss
  hostplat-client/src/app/labels/label-details/label-details.component.ts
  hostplat-client/src/app/labels/label.module.ts
  hostplat-client/src/app/labels/label.service.ts
  hostplat-client/src/app/labels/update-label/update-label.component.html
  hostplat-client/src/app/labels/update-label/update-label.component.scss
  hostplat-client/src/app/labels/update-label/update-label.component.spec.ts
  hostplat-client/src/app/labels/update-label/update-label.component.ts
  hostplat-client/src/app/milestones/update-milestone/update-milestone.component.ts
  hostplat-client/src/app/models/label-task.model.ts
  hostplat-client/src/app/models/label.model.ts
  hostplat-client/src/app/projects/project-details/project-details.component.html
  hostplat-client/src/app/projects/project-details/project-details.component.ts
  hostplat-client/src/app/projects/project.service.ts
  hostplat-client/src/app/tasks/task-details/task-details.component.html
  hostplat-client/src/app/tasks/task-details/task-details.component.ts
  hostplat-client/src/app/tasks/task.service.ts
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/ProjectController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/TaskController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/LabelTaskDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/TaskService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/MilestoneServiceImpl.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/ProjectServiceImpl.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/TaskServiceImpl.java
Labels: back-end, front-end

#110 hostplat project update with new features
  hostplat-client/src/app/app-routing.module.ts
  hostplat-client/src/app/app.module.ts
  hostplat-client/src/app/core/services/user.service.ts
  hostplat-client/src/app/labels/add-label/add-label.component.html
  hostplat-client/src/app/labels/add-label/add-label.component.scss
  hostplat-client/src/app/labels/add-label/add-label.component.spec.ts
  hostplat-client/src/app/labels/add-label/add-label.component.ts
  hostplat-client/src/app/labels/label-details/labal-details.component.spec.ts
  hostplat-client/src/app/labels/label-details/label-details.component.html
  hostplat-client/src/app/labels/label-details/label-details.component.scss
  hostplat-client/src/app/labels/label-details/label-details.component.ts
  hostplat-client/src/app/labels/label.module.ts
  hostplat-client/src/app/labels/label.service.ts
  hostplat-client/src/app/labels/update-label/update-label.component.html
  hostplat-client/src/app/labels/update-label/update-label.component.scss
  hostplat-client/src/app/labels/update-label/update-label.component.spec.ts
  hostplat-client/src/app/labels/update-label/update-label.component.ts
  hostplat-client/src/app/milestones/update-milestone/update-milestone.component.ts
  hostplat-client/src/app/models/label-task.model.ts
  hostplat-client/src/app/models/label.model.ts
  hostplat-client/src/app/models/statisticBack.model.ts
  hostplat-client/src/app/models/statistics.model.ts
  hostplat-client/src/app/models/user.ts
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.css
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.html
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.spec.ts
  hostplat-client/src/app/pages/home-page-dialog/home-page-dialog.component.ts
  hostplat-client/src/app/pages/home-page/home-page.component.css
  hostplat-client/src/app/pages/home-page/home-page.component.html
  hostplat-client/src/app/pages/home-page/home-page.component.ts
  hostplat-client/src/app/pages/pages.module.ts
  hostplat-client/src/app/projects/project-details/project-details.component.html
  hostplat-client/src/app/projects/project-details/project-details.component.scss
  hostplat-client/src/app/projects/project-details/project-details.component.ts
  hostplat-client/src/app/projects/project.service.ts
  hostplat-client/src/app/tasks/task-details/task-details.component.html
  hostplat-client/src/app/tasks/task-details/task-details.component.ts
  hostplat-client/src/app/tasks/task.service.ts
  hostplat-client/src/app/user/change-avatar/change-avatar.component.css
  hostplat-client/src/app/user/change-avatar/change-avatar.component.html
  hostplat-client/src/app/user/change-avatar/change-avatar.component.ts
  hostplat-client/src/app/user/change-basic-info/change-basic-info.component.ts
  hostplat-client/src/environments/environment.ts
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/CloudinaryConfig.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/WebSecurityConfig.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/ProjectController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/TaskController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/UserController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/LabelTaskDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/StatisticBackDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/dto/StatisticsDTO.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/ProjectService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/TaskService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/UserService.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/MilestoneServiceImpl.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/ProjectServiceImpl.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/TaskServiceImpl.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/UserServiceImpl.java
  hostplat-server/src/main/resources/application.yaml
Labels: back-end, devops, front-end

#116 tests update
  Jenkinsfile
  hostplat-server/pom.xml
  hostplat-server/src/main/resources/application-test.yaml
  hostplat-server/src/main/resources/logback-test.xml
Labels: devops

#117 Develop to Master Release
  Jenkinsfile
  hostplat-server/pom.xml
  hostplat-server/src/main/resources/application-test.yaml
  hostplat-server/src/main/resources/logback-test.xml
Labels: devops

#121 Develop to Master
  hostplat-server/src/test/java/uns/ac/rs/hostplatserver/service/ProjectServiceIntegrationTest.java
Labels: bug

#122 telegraf
  config/telegraf/telegraf.conf
  docker-compose.yml
Labels: devops

#123 Develop to Master - Telegraf
  config/telegraf/telegraf.conf
  docker-compose.yml
Labels: devops

#124 fix public endpoint
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/WebSecurityConfig.java
Labels: back-end

#125 Develop to Master Release - Public Endpoint Fix
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/config/WebSecurityConfig.java
Labels: back-end

#128 Develop to Master Final Release
  documentation/model.png
  hostplat-client/src/app/app-routing.module.ts
  hostplat-client/src/app/app.module.ts
  hostplat-client/src/app/projects/kanban/kanban.component.css
  hostplat-client/src/app/projects/kanban/kanban.component.html
  hostplat-client/src/app/projects/kanban/kanban.component.spec.ts
  hostplat-client/src/app/projects/kanban/kanban.component.ts
  hostplat-client/src/app/projects/project-list-item/project-list-item.component.html
  hostplat-client/src/app/projects/project-list-item/project-list-item.component.ts
  hostplat-client/src/app/projects/project.module.ts
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/controller/ProjectController.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/Milestone.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/Project.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/Task.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/model/Wiki.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/MilestoneServiceImpl.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/ProjectServiceImpl.java
  hostplat-server/src/main/java/uns/ac/rs/hostplatserver/service/impl/TaskServiceImpl.java
  hostplat-server/src/test/java/uns/ac/rs/hostplatserver/service/UserServiceUnitTest.java
Labels: back-end, release
